export const OldLicenseeCode = {
  0x00: { code: 0x00, publisher: 'None' },
  0x01: { code: 0x01, publisher: 'Nintendo' },
  0x08: { code: 0x08, publisher: 'Capcom' },
  0x09: { code: 0x09, publisher: 'Hot-B' },
  0x0A: { code: 0x0A, publisher: 'Jaleco' },
  0x0B: { code: 0x0B, publisher: 'Coconuts Japan' },
  0x0C: { code: 0x0C, publisher: 'Elite Systems' },
  0x13: { code: 0x13, publisher: 'EA (Electronic Arts)' },
  0x18: { code: 0x18, publisher: 'Hudsonsoft' },
  0x19: { code: 0x19, publisher: 'ITC Entertainment' },
  0x1A: { code: 0x1A, publisher: 'Yanoman' },
  0x1D: { code: 0x1D, publisher: 'Japan Clary' },
  0x1F: { code: 0x1F, publisher: 'Virgin Interactive' },
  0x24: { code: 0x24, publisher: 'PCM Complete' },
  0x25: { code: 0x25, publisher: 'San-X' },
  0x28: { code: 0x28, publisher: 'Kotobuki Systems' },
  0x29: { code: 0x29, publisher: 'Seta' },
  0x30: { code: 0x30, publisher: 'Infogrames' },
  0x31: { code: 0x31, publisher: 'Nintendo' },
  0x32: { code: 0x32, publisher: 'Bandai' },
  0x33: { code: 0x33, publisher: 'Indicates that the [New licensee<#0144-0145 - New licensee should be used instead.' },
  0x34: { code: 0x34, publisher: 'Konami' },
  0x35: { code: 0x35, publisher: 'HectorSoft' },
  0x38: { code: 0x38, publisher: 'Capcom' },
  0x39: { code: 0x39, publisher: 'Banpresto' },
  0x3C: { code: 0x3C, publisher: '.Entertainment i' },
  0x3E: { code: 0x3E, publisher: 'Gremlin' },
  0x41: { code: 0x41, publisher: 'Ubisoft' },
  0x42: { code: 0x42, publisher: 'Atlus' },
  0x44: { code: 0x44, publisher: 'Malibu' },
  0x46: { code: 0x46, publisher: 'Angel' },
  0x47: { code: 0x47, publisher: 'Spectrum Holoby' },
  0x49: { code: 0x49, publisher: 'Irem' },
  0x4A: { code: 0x4A, publisher: 'Virgin Interactive' },
  0x4D: { code: 0x4D, publisher: 'Malibu' },
  0x4F: { code: 0x4F, publisher: 'U.S. Gold' },
  0x50: { code: 0x50, publisher: 'Absolute' },
  0x51: { code: 0x51, publisher: 'Acclaim' },
  0x52: { code: 0x52, publisher: 'Activision' },
  0x53: { code: 0x53, publisher: 'American Sammy' },
  0x54: { code: 0x54, publisher: 'GameTek' },
  0x55: { code: 0x55, publisher: 'Park Place' },
  0x56: { code: 0x56, publisher: 'LJN' },
  0x57: { code: 0x57, publisher: 'Matchbox' },
  0x59: { code: 0x59, publisher: 'Milton Bradley' },
  0x5A: { code: 0x5A, publisher: 'Mindscape' },
  0x5B: { code: 0x5B, publisher: 'Romstar' },
  0x5C: { code: 0x5C, publisher: 'Naxat Soft' },
  0x5D: { code: 0x5D, publisher: 'Tradewest' },
  0x60: { code: 0x60, publisher: 'Titus' },
  0x61: { code: 0x61, publisher: 'Virgin Interactive' },
  0x67: { code: 0x67, publisher: 'Ocean Interactive' },
  0x69: { code: 0x69, publisher: 'EA (Electronic Arts)' },
  0x6E: { code: 0x6E, publisher: 'Elite Systems' },
  0x6F: { code: 0x6F, publisher: 'Electro Brain' },
  0x70: { code: 0x70, publisher: 'Infogrames' },
  0x71: { code: 0x71, publisher: 'Interplay' },
  0x72: { code: 0x72, publisher: 'Broderbund' },
  0x73: { code: 0x73, publisher: 'Sculptered Soft' },
  0x75: { code: 0x75, publisher: 'The Sales Curve' },
  0x78: { code: 0x78, publisher: 't.hq' },
  0x79: { code: 0x79, publisher: 'Accolade' },
  0x7A: { code: 0x7A, publisher: 'Triffix Entertainment' },
  0x7C: { code: 0x7C, publisher: 'Microprose' },
  0x7F: { code: 0x7F, publisher: 'Kemco' },
  0x80: { code: 0x80, publisher: 'Misawa Entertainment' },
  0x83: { code: 0x83, publisher: 'Lozc' },
  0x86: { code: 0x86, publisher: 'Tokuma Shoten Intermedia' },
  0x8B: { code: 0x8B, publisher: 'Bullet-Proof Software' },
  0x8C: { code: 0x8C, publisher: 'Vic Tokai' },
  0x8E: { code: 0x8E, publisher: 'Ape' },
  0x8F: { code: 0x8F, publisher: 'I’Max' },
  0x91: { code: 0x91, publisher: 'Chunsoft Co.' },
  0x92: { code: 0x92, publisher: 'Video System' },
  0x93: { code: 0x93, publisher: 'Tsubaraya Productions Co.' },
  0x95: { code: 0x95, publisher: 'Varie Corporation' },
  0x96: { code: 0x96, publisher: 'Yonezawa/S’Pal' },
  0x97: { code: 0x97, publisher: 'Kaneko' },
  0x99: { code: 0x99, publisher: 'Arc' },
  0x9A: { code: 0x9A, publisher: 'Nihon Bussan' },
  0x9B: { code: 0x9B, publisher: 'Tecmo' },
  0x9C: { code: 0x9C, publisher: 'Imagineer' },
  0x9D: { code: 0x9D, publisher: 'Banpresto' },
  0x9F: { code: 0x9F, publisher: 'Nova' },
  0xA1: { code: 0xA1, publisher: 'Hori Electric' },
  0xA2: { code: 0xA2, publisher: 'Bandai' },
  0xA4: { code: 0xA4, publisher: 'Konami' },
  0xA6: { code: 0xA6, publisher: 'Kawada' },
  0xA7: { code: 0xA7, publisher: 'Takara' },
  0xA9: { code: 0xA9, publisher: 'Technos Japan' },
  0xAA: { code: 0xAA, publisher: 'Broderbund' },
  0xAC: { code: 0xAC, publisher: 'Toei Animation' },
  0xAD: { code: 0xAD, publisher: 'Toho' },
  0xAF: { code: 0xAF, publisher: 'Namco' },
  0xB0: { code: 0xB0, publisher: 'acclaim' },
  0xB1: { code: 0xB1, publisher: 'ASCII or Nexsoft' },
  0xB2: { code: 0xB2, publisher: 'Bandai' },
  0xB4: { code: 0xB4, publisher: 'Square Enix' },
  0xB6: { code: 0xB6, publisher: 'HAL Laboratory' },
  0xB7: { code: 0xB7, publisher: 'SNK' },
  0xB9: { code: 0xB9, publisher: 'Pony Canyon' },
  0xBA: { code: 0xBA, publisher: 'Culture Brain' },
  0xBB: { code: 0xBB, publisher: 'Sunsoft' },
  0xBD: { code: 0xBD, publisher: 'Sony Imagesoft' },
  0xBF: { code: 0xBF, publisher: 'Sammy' },
  0xC0: { code: 0xC0, publisher: 'Taito' },
  0xC2: { code: 0xC2, publisher: 'Kemco' },
  0xC3: { code: 0xC3, publisher: 'Squaresoft' },
  0xC4: { code: 0xC4, publisher: 'Tokuma Shoten Intermedia' },
  0xC5: { code: 0xC5, publisher: 'Data East' },
  0xC6: { code: 0xC6, publisher: 'Tonkinhouse' },
  0xC8: { code: 0xC8, publisher: 'Koei' },
  0xC9: { code: 0xC9, publisher: 'UFL' },
  0xCA: { code: 0xCA, publisher: 'Ultra' },
  0xCB: { code: 0xCB, publisher: 'Vap' },
  0xCC: { code: 0xCC, publisher: 'Use Corporation' },
  0xCD: { code: 0xCD, publisher: 'Meldac' },
  0xCE: { code: 0xCE, publisher: '.Pony Canyon or' },
  0xCF: { code: 0xCF, publisher: 'Angel' },
  0xD0: { code: 0xD0, publisher: 'Taito' },
  0xD1: { code: 0xD1, publisher: 'Sofel' },
  0xD2: { code: 0xD2, publisher: 'Quest' },
  0xD3: { code: 0xD3, publisher: 'Sigma Enterprises' },
  0xD4: { code: 0xD4, publisher: 'ASK Kodansha Co.' },
  0xD6: { code: 0xD6, publisher: 'Naxat Soft' },
  0xD7: { code: 0xD7, publisher: 'Copya System' },
  0xD9: { code: 0xD9, publisher: 'Banpresto' },
  0xDA: { code: 0xDA, publisher: 'Tomy' },
  0xDB: { code: 0xDB, publisher: 'LJN' },
  0xDD: { code: 0xDD, publisher: 'NCS' },
  0xDE: { code: 0xDE, publisher: 'Human' },
  0xDF: { code: 0xDF, publisher: 'Altron' },
  0xE0: { code: 0xE0, publisher: 'Jaleco' },
  0xE1: { code: 0xE1, publisher: 'Towa Chiki' },
  0xE2: { code: 0xE2, publisher: 'Yutaka' },
  0xE3: { code: 0xE3, publisher: 'Varie' },
  0xE5: { code: 0xE5, publisher: 'Epcoh' },
  0xE7: { code: 0xE7, publisher: 'Athena' },
  0xE8: { code: 0xE8, publisher: 'Asmik ACE Entertainment' },
  0xE9: { code: 0xE9, publisher: 'Natsume' },
  0xEA: { code: 0xEA, publisher: 'King Records' },
  0xEB: { code: 0xEB, publisher: 'Atlus' },
  0xEC: { code: 0xEC, publisher: 'Epic/Sony Records' },
  0xEE: { code: 0xEE, publisher: 'IGS' },
  0xF0: { code: 0xF0, publisher: 'A Wave' },
  0xF3: { code: 0xF3, publisher: 'Extreme Entertainment' },
  0xFF: { code: 0xFF, publisher: 'LJN' },
};
